name: ai_image_compare
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image: ^4.0.17  # For decodeImageFromList
  camera: ^0.10.0+1
  image_picker: ^0.8.7+3
  permission_handler: ^12.0.0+1
  permission_handler_android: ^13.0.0
  http: ^1.4.0
  flutter_dotenv: ^5.0.2
  google_ml_kit: ^0.20.0
  google_mlkit_barcode_scanning: ^0.14.1
  google_mlkit_face_detection: ^0.13.1
  google_mlkit_text_recognition: ^0.15.0
  google_mlkit_image_labeling: ^0.14.1
  google_mlkit_object_detection: ^0.15.0
  google_mlkit_pose_detection: ^0.14.0
  google_mlkit_selfie_segmentation: ^0.10.0
  clipboard: ^0.1.3
  google_mlkit_translation: ^0.13.0
  google_translator: ^1.0.0
  translator: ^1.0.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env