name: ai_image_compare
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  camera: ^0.10.0+1
  image_picker: ^0.8.7+3
  permission_handler: ^12.0.0+1
  permission_handler_android: ^13.0.0
  http: ^1.4.0
  google_ml_kit: ^0.20.0
  flutter_dotenv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true